### ISSUE TITLE
Not compatible with Angular 15 

### ISSUE THREAD

**Issue by yatinmob** [thekip/angular-cc-library#114]

**Comment by thekip** [comment]
It's probably just a matter of bumping a deps in the package json. The code itself should be 100% compatible. I will bump soon

**Comment by wen9218** [comment]
@thekip, me, too
angular-cc-library is not compatible with Ng v15.
when could you possibly release a new version?

**Comment by born2net** [comment]
please help... we really need to move to v15... TX for a great lib!

**Comment by thekip** [comment]
Published 3.0.2

**Comment by wen9218** [comment]
@thekip, sorry, I can't find new release. please check again

**Comment by thekip** [comment]
https://www.npmjs.com/package/angular-cc-library/v/3.0.2

**Comment by thekip** [comment]
It's turned out that distributable created with Angular 15 compiler is not compatible with angular 14 apps. So release 3.0.2 broke compatibility. 

I reverted Angular 15 in the {patch} version, and created a new 3.0.4 (i skipped 3.0.3 because accidentally published the same version as 3.0.2) which works with angular 14.

Angular 15 Release now is 3.1.0 https://github.com/thekip/angular-cc-library/releases/tag/v3.1.0

I've added version compatibility table to Readme. 


Sorry for this mess, I didn't find anywhere in Angular docs or upgrade guides that there would be incompatibilities in the libs between v14 - v15.
